{
    "name": "Hospital management system",
    "summary": "Sistema de gestión hospitalaria",
    "version": "18.0.0.1.0",
    "category": "Other",
    "website": "https://cuidamet.duckdns.org/",
    "author": "SocGer",
    "license": "LGPL-3",
    "depends": ["base", "mail", "product", "account"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/patient_views.xml",
        "views/patient_readonly_views.xml",
        "views/appointment_views.xml",
        "views/appointment_line_views.xml",
        "views/patient_tag_views.xml",
        "views/account_move_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
