from . import test_vehicle_type
from . import test_concept_cost_budget_sale_family
from . import test_concept_cost_budget_sale
from . import test_concept_cost_budget_sale_by_vehicle_type
from . import test_vehicle_feature_category
from . import test_vehicle_feature
from . import test_vehicle_feature_by_vehicle
from . import test_fleet_vehicle_document_category
from . import test_attachment_fleet_document
from . import test_fleet_garage
from . import test_fleet_vehicle_garage
from . import test_fleet_vehicle
from . import test_fleet_vehicle_views
