{
    "name": "Socger Expand Fleet",
    "summary": "Gestión que expandela flota de vehículos",
    "version": "18.0.0.19.0",
    "category": "Human Resources/Fleet",
    "website": "https://cuidamet.duckdns.org/",
    "author": "SocGer",
    "license": "LGPL-3",
    "depends": ["fleet"],
    "post_init_hook": "post_init_hook",
    "data": [
        "security/ir.model.access.csv",
        "views/vehicle_type_views.xml",
        "views/concept_cost_budget_sale_family_views.xml",
        "views/concept_cost_budget_sale_views.xml",
        "views/concept_cost_budget_sale_by_vehicle_type_views.xml",
        "views/vehicle_feature_category_views.xml",
        "views/vehicle_feature_views.xml",
        "views/vehicle_feature_by_vehicle_views.xml",
        "views/fleet_vehicle_document_views.xml",
        "views/fleet_vehicle_document_category_views.xml",
        "views/fleet_vehicle_model_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/concept_cost_budget_sale_by_vehicle_views.xml",
        "views/report.xml",
        "views/report_templates.xml",
        "views/report_basic_templates.xml",
        "views/report_by_vehicle_type_templates.xml",
        "views/report_by_vehicle_type_basic_templates.xml",
        "views/report_vehicle_type_templates.xml",
        "views/report_vehicle_type_basic_templates.xml",
        "views/report_concept_cost_budget_sale_templates.xml",
        "views/report_concept_cost_budget_sale_basic_templates.xml",
        "views/report_vehicle_feature_category_templates.xml",
        "views/report_vehicle_feature_category_basic_templates.xml",
        "views/report_vehicle_feature_templates.xml",
        "views/report_vehicle_feature_basic_templates.xml",
        "views/report_vehicle_feature_by_vehicle_templates.xml",
        "views/report_vehicle_feature_by_vehicle_basic_templates.xml",
        "views/fleet_garage_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "socger_expand_fleet/static/src/components/attachment_preview.esm.js",
            "socger_expand_fleet/static/src/components/attachment_preview.xml",
            "socger_expand_fleet/static/src/components/attachment_preview.scss",
            "socger_expand_fleet/static/src/widgets/attachment_preview_field.esm.js",
            "socger_expand_fleet/static/src/widgets/attachment_preview_field.xml",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
