{
    "name": "Socger Expand Fleet",
    "summary": "Gestión que expandela flota de vehículos",
    "version": "18.0.0.7.0",
    "category": "Human Resources/Fleet",
    "website": "https://cuidamet.duckdns.org/",
    "author": "SocGer",
    "license": "LGPL-3",
    "depends": ["fleet"],
    "data": [
        "security/ir.model.access.csv",
        "views/vehicle_type_views.xml",
        "views/concept_cost_budget_sale_family_views.xml",
        "views/concept_cost_budget_sale_views.xml",
        "views/concept_cost_budget_sale_by_vehicle_type_views.xml",
        "views/vehicle_feature_category_views.xml",
        "views/vehicle_feature_views.xml",
        "views/vehicle_feature_by_vehicle_views.xml",
        "views/fleet_vehicle_document_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
